# Generated by Django 3.2.20 on 2023-07-15 17:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
