# Generated by Django 3.2.20 on 2023-07-16 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230715_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='accounts', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
