# Generated by Django 3.2.20 on 2023-07-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'ordering': ('-date',)},
        ),
    ]
